version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: pdogs
    networks:
      - internal

  flyway:
    image: flyway/flyway:latest-alpine
    command: migrate
    depends_on:
      - db
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/pdogs
      FLYWAY_USER: dev
      FLYWAY_PASSWORD: dev
    volumes:
      - ./sql:/flyway/sql
    networks:
      - internal

networks:
  internal:
