version: '3'

services:
  pws_database:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: pdogs
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d
    networks:
      - internal
  minio:
    image: quay.io/minio/minio:latest
    container_name: pws-minio
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ~/minio/data:/data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: sheetExtractor
      MINIO_ROOT_PASSWORD: sheetExtractor
    command: server /data --address ":8080" --console-address ":8081"
networks:
  internal:
